baseURL: "https://symphonious-puffpuff-d7704c.netlify.app/"
languageCode: en-us
title: My Blogs
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Hai there, I'm Varshith V Hegde 👋"
    Content: "Welcome to my blog"
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://raw.githubusercontent.com/Varshithvhegde/Varshithvhegde.github.io/main/assets/favicon.ico"
  socialIcons: 
    - name: github
      url: 'https://github.com/Varshithvhegde'
    - name: website
      url: 'https://Varshithvhegde.github.io'
    - name: linkedin
      url: 'https://linkedin.com/in/varshithvhegde'
    - name: dev
      url: 'https://dev.to/Varshithvhegde'
    - name: email
      url: 'mailto:varshithvh@gmail.com'
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowToc: true

menu:
  main:
  - identifier: home
    name: Home
    url: https://varshithvhegde.me
    weight: 10  

