baseURL: "https://symphonious-puffpuff-d7704c.netlify.app/"
languageCode: en-us
title: My Blogs
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "Hai there, I'm Varshith V Hegde 👋"
    Content: "Welcome to my blog"
  socialIcons: 
    - name: github
      url: 'https://github.com/Varshithvhegde'
    - name: website
      url: 'https://Varshithvhegde.github.io'
    - name: linkedin
      url: 'https://linkedin.com/in/varshithvhegde'
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowToc: true

menu:
  main:
  - identifier: home
    name: Home
    url: https://varshithvhegde.me
    weight: 10
  - identifier: search
    name: Search
    url: content/search.md
    weight: 10

